spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true

